spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: 123456
    #driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall
      aop-patterns: com.zkh.admin.*

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'     #默认排除这些文件

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
